services:
  redis:
    image: redis:8
    expose:
      - "6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

    healthcheck:
      test: ["CMD-SHELL", "REDISCLI_AUTH=$${REDIS_PASSWORD} redis-cli ping"]
      interval: 2s
      timeout: 5s
      retries: 5

  db:
      image: postgres:16
      restart: always
      environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      volumes:
        - postgres_data:/var/lib/postgresql/data
      ports:
        - "5432:5432"

      healthcheck:
        test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB}"]
        interval: 2s
        timeout: 5s
        retries: 5
        start_period: 3s

  db-migration:
    image: "ghcr.io/user01377/bme-database-migration:${SHA:-prod}"
    depends_on:
      db:
        condition: service_healthy
    command: alembic upgrade head
    env_file:
      - .env

  data-receiver-migration:
    image: "ghcr.io/user01377/bme-data-receiver:${SHA:-prod}"
    volumes:
      - receiver_data:/data
    command: alembic upgrade head
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/devices.db

  data-receiver:
    image: "ghcr.io/user01377/bme-data-receiver:${SHA:-prod}"
    volumes:
      - receiver_data:/data
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/devices.db
    
    depends_on:
      data-receiver-migration:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
  
  database-handler-in:
    image: "ghcr.io/user01377/bme-handler-in:${SHA:-prod}"
    env_file:
      - .env

    depends_on:
      db-migration:
        condition: service_completed_successfully
  
  database-handler-out:
    image: "ghcr.io/user01377/bme-handler-out:${SHA:-prod}"
    expose:
      - "8002"
    env_file:
      - .env

    depends_on:
      db-migration:
        condition: service_completed_successfully

  data-server-migration:
    image: "ghcr.io/user01377/bme-data-server:${SHA:-prod}"
    volumes:
      - server_data:/data
    command: alembic upgrade head
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/data-server.db
  
  data-server:
    image: "ghcr.io/user01377/bme-data-server:${SHA:-prod}"
    volumes:
      - server_data:/data
    ports:
      - "8003:8003"
    env_file:
      - .env
    environment:
      DATABASE_URL: sqlite:////data/data-server.db

    depends_on:
      data-server-migration:
        condition: service_completed_successfully

        
volumes:
  postgres_data:
  receiver_data:
  server_data: