"""Create device tables

Revision ID: b1c3acc7a997
Revises: 
Create Date: 2026-09-12 20:28:57.169429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c3acc7a997'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('device_id'),
    sa.UniqueConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devices')
    # ### end Alembic commands ###
