[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bme-handler-in"
version = "0.1.0"
description = "The microservice which manipulates data from the redis queue and stores the data into database"

requires-python = ">=3.12"
dependencies=[
    "redis",
    "pydantic",
    "sqlalchemy",
    "pyyaml",
    "psycopg[binary]"
]

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-mock"
]