"""Create diagnostic table

Revision ID: 446c1c9b3791
Revises: 41bb8e61a7a4
Create Date: 2026-10-03 07:25:38.518873

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446c1c9b3791'
down_revision: Union[str, Sequence[str], None] = '41bb8e61a7a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostic_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('uptime', sa.Integer(), nullable=False),
    sa.Column('reset', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnostic_data')
    # ### end Alembic commands ###
