name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
    # backend testing implementation

    push-image:
        name: Build Backend Image
        if: github.ref == 'refs/heads/main'
        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repo
            uses: actions/checkout@v4
        
          - name: GHCR Login
            uses: docker/login-action@v3
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
    
          - name: Build Data Receiver Image
            run: |
              docker build \
                -t ghcr.io/user01377/bme-data-receiver:${{ github.sha }} \
                -t ghcr.io/user01377/bme-data-receiver:prod \
                services/data-receiver
          
          - name: Build Database Handler In Image
            run: |
              docker build \
                -t ghcr.io/user01377/bme-handler-in:${{ github.sha }} \
                -t ghcr.io/user01377/bme-handler-in:prod \
                services/database-handler-in

          - name: Build Database Handler Out Image
            run: |
              docker build \
                -t ghcr.io/user01377/bme-handler-out:${{ github.sha }} \
                -t ghcr.io/user01377/bme-handler-out:prod \
                services/database-handler-out

          - name: Build Data Server Image
            run: |
              docker build \
                -t ghcr.io/user01377/bme-data-server:${{ github.sha }} \
                -t ghcr.io/user01377/bme-data-server:prod \
                services/data-server
          
          - name: Build Database Migration Image
            run: |
              docker build \
                -t ghcr.io/user01377/bme-database-migration:${{ github.sha }} \
                -t ghcr.io/user01377/bme-database-migration:prod \
                database
    
          - name: Push Images To Registry
            run: |
                docker push ghcr.io/user01377/bme-data-receiver:${{ github.sha }}
                docker push ghcr.io/user01377/bme-data-receiver:prod
                docker push ghcr.io/user01377/bme-handler-in:${{ github.sha }}
                docker push ghcr.io/user01377/bme-handler-in:prod
                docker push ghcr.io/user01377/bme-handler-out:${{ github.sha }}
                docker push ghcr.io/user01377/bme-handler-out:prod
                docker push ghcr.io/user01377/bme-data-server:${{ github.sha }}
                docker push ghcr.io/user01377/bme-data-server:prod
                docker push ghcr.io/user01377/bme-database-migration:${{ github.sha }}
                docker push ghcr.io/user01377/bme-database-migration:prod